// GOOGLE MAPS API REQUESTS
// Geolocation of user
POST https://www.googleapis.com/geolocation/v1/geolocate?key={{api_key}}
###

// Static map
GET https://maps.googleapis.com/maps/api/staticmap?
    size=640x400&
    center=44.4136524%2C26.0678231&
    zoom=15&
    maptype=roadmap&
    markers=color:blue%7C44.4136524%2C26.0678231&
    key={{api_key}}
###

// KTOR REQUESTS

// Get branches
GET http://localhost/api/all?location=44.410632%2C26.066814
###

// Get days for branch
GET http://localhost/api/days/310
###

// Get timeslots for branch and day
GET http://localhost/api/timeslots/310?date=2022-12-12
###

// Submit
POST http://localhost/api/submit
Content-Type: application/json

{
    "actions": "Deschidere cont",
    "branchID": 202,
    "date": "2022-12-12",
    "time": "16:00",
    "name": "Koleci",
    "surname": "Alexandru",
    "cnp": "5123456000000",
    "email": "email@example.ro",
    "phone": "0712323123"
}
###

// Cancel (put key here from Appointments table in database)
GET http://localhost/email/cancelAppointment?key=
###